version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - techhome-network

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: techhome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - techhome-network

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - techhome-network

volumes:
  postgres-data:
  redis-data:

networks:
  techhome-network:
