version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - techhome-network

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: techhome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - techhome-network

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - techhome-network
 
  # nginx:
  #   image: nginx:alpine
  #   depends_on:
  #     - app
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./letsencrypt:/etc/letsencrypt
  #     - ./nginx/logs:/var/log/nginx
  #   networks:
  #     - techhome-network

  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./letsencrypt:/etc/letsencrypt
  #     - ./certbot/logs:/var/log/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 2073600; done'

volumes:
  postgres-data:
  redis-data:

networks:
  techhome-network:
